name:                neatup
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/neatup#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2019 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - scotty
  - text
  - mime-types
  - bytestring

executables:
  neatup:
    source-dirs:      src
    main:             Main.hs
